/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Serializer to add/remove object roles to/from users/groups.
 *
 * This is used in conjunction with ``pulpcore.app.viewsets.base.RolesMixin`` and requires the
 * underlying object to be passed as ``content_object`` in the context.
 */
export interface NestedRole {
	/** @items.minLength 1 */
	users?: string[];
	/** @items.minLength 1 */
	groups?: string[];
	/** @minLength 1 */
	role: string;
}
