/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { NestedRoleResponse } from "./nestedRoleResponse";

export interface ObjectRolesResponse {
	roles: NestedRoleResponse[];
}
