version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    open-pull-requests-limit: 10
    groups:
      vite-swc:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "@swc/*"
        lingui:
          - "@lingui/*"
        react:
          patterns:
            - "react"
            - "react-dom"
        tanstack:
          patterns:
            - "@tanstack/*"
        testing:
          patterns:
            - "vitest"
            - "@vitest/*"
            - "@testing-library/*"
            - "@playwright/*"
            - "jsdom"
            - "msw"
        biome:
          patterns:
            - "@biomejs/*"
        security-patches:
          applies-to: security-updates
          patterns:
            - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"
