nodeVersion: "24.14.0"
saveExact: true
packages:
  - "packages/*"
minimumReleaseAge: 10080 # 7 Days
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600 # 90 days
blockExoticSubdeps: true
engineStrict: true
catalog:
  typescript: 7.0.2
  "@types/node": 26.2.0
overrides:
  "@swc/core": 1.15.40
minimumReleaseAgeExclude:
  - vite@8.2.2
  - '@biomejs/biome@2.5.10'
  - '@biomejs/cli-darwin-arm64@2.5.10'
  - '@biomejs/cli-darwin-x64@2.5.10'
  - '@biomejs/cli-linux-arm64-musl@2.5.10'
  - '@biomejs/cli-linux-arm64@2.5.10'
  - '@biomejs/cli-linux-x64-musl@2.5.10'
  - '@biomejs/cli-linux-x64@2.5.10'
  - '@biomejs/cli-win32-arm64@2.5.10'
  - '@biomejs/cli-win32-x64@2.5.10'
  - '@types/react-dom@19.2.5'
  - '@tanstack/react-router@1.170.32'
  - '@tanstack/router-core@1.171.27'
allowBuilds:
  '@swc/core': true
