/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Serializer for asynchronous operations.
 */
export interface AsyncOperationResponse {
	/** The href of the task. */
	task: string;
}
