/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

export interface PatchedTaskCancel {
	/**
	 * The desired state of the task. Only 'canceled' is accepted.
	 * @minLength 1
	 */
	state?: string;
}
