/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Base serializer for use with [pulpcore.app.models.Model][]
 *
 * This ensures that all Serializers provide values for the 'pulp_href` field.
 *
 * The class provides a default for the ``ref_name`` attribute in the
 * ModelSerializers's ``Meta`` class. This ensures that the OpenAPI definitions
 * of plugins are namespaced properly.
 */
export interface ProgressReportResponse {
	/** The message shown to the user for the progress report. */
	readonly message?: string;
	/** Identifies the type of progress report'. */
	readonly code?: string;
	/** The current state of the progress report. The possible values are: 'waiting', 'skipped', 'running', 'completed', 'failed', 'canceled' and 'canceling'. The default is 'waiting'. */
	readonly state?: string;
	/** The total count of items. */
	readonly total?: number;
	/** The count of items already processed. Defaults to 0. */
	readonly done?: number;
	/**
	 * The suffix to be shown with the progress report.
	 * @nullable
	 */
	readonly suffix?: string | null;
}
