/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { StatesEnum } from "./statesEnum";

export interface Purge {
	/** Purge tasks completed earlier than this timestamp. Format '%Y-%m-%d[T%H:%M:%S]' */
	finished_before?: string;
	/** List of task-states to be purged. Only 'final' states are allowed. */
	states?: StatesEnum[];
}
