/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * * `skipped` - skipped
 * * `completed` - completed
 * * `failed` - failed
 * * `canceled` - canceled
 */
export type StatesEnum = (typeof StatesEnum)[keyof typeof StatesEnum];

export const StatesEnum = {
	skipped: "skipped",
	completed: "completed",
	failed: "failed",
	canceled: "canceled",
} as const;
