/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

export type TasksListOrderingItem =
	(typeof TasksListOrderingItem)[keyof typeof TasksListOrderingItem];

export const TasksListOrderingItem = {
	"-deferred": "-deferred",
	"-enc_args": "-enc_args",
	"-enc_kwargs": "-enc_kwargs",
	"-error": "-error",
	"-finished_at": "-finished_at",
	"-immediate": "-immediate",
	"-logging_cid": "-logging_cid",
	"-name": "-name",
	"-pk": "-pk",
	"-profile_options": "-profile_options",
	"-pulp_created": "-pulp_created",
	"-pulp_id": "-pulp_id",
	"-pulp_last_updated": "-pulp_last_updated",
	"-reserved_resources_record": "-reserved_resources_record",
	"-result": "-result",
	"-started_at": "-started_at",
	"-state": "-state",
	"-unblocked_at": "-unblocked_at",
	"-versions": "-versions",
	deferred: "deferred",
	enc_args: "enc_args",
	enc_kwargs: "enc_kwargs",
	error: "error",
	finished_at: "finished_at",
	immediate: "immediate",
	logging_cid: "logging_cid",
	name: "name",
	pk: "pk",
	profile_options: "profile_options",
	pulp_created: "pulp_created",
	pulp_id: "pulp_id",
	pulp_last_updated: "pulp_last_updated",
	reserved_resources_record: "reserved_resources_record",
	result: "result",
	started_at: "started_at",
	state: "state",
	unblocked_at: "unblocked_at",
	versions: "versions",
} as const;
