/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

export type TasksListState =
	(typeof TasksListState)[keyof typeof TasksListState];

export const TasksListState = {
	canceled: "canceled",
	canceling: "canceling",
	completed: "completed",
	failed: "failed",
	running: "running",
	skipped: "skipped",
	waiting: "waiting",
} as const;
