/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * A JSON Object of a fatal error encountered during the execution of this task.
 */
export type TaskResponseError = { [key: string]: unknown };
