/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { ProgressReportResponse } from "./progressReportResponse";
import type { TaskResponseError } from "./taskResponseError";

/**
 * Base serializer for use with [pulpcore.app.models.Model][]
 *
 * This ensures that all Serializers provide values for the 'pulp_href` field.
 *
 * The class provides a default for the ``ref_name`` attribute in the
 * ModelSerializers's ``Meta`` class. This ensures that the OpenAPI definitions
 * of plugins are namespaced properly.
 */
export interface TaskResponse {
	readonly pulp_href?: string;
	/** The Pulp Resource Name (PRN). */
	readonly prn?: string;
	/** Timestamp of creation. */
	readonly pulp_created?: string;
	/** Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same. */
	readonly pulp_last_updated?: string;
	/** The current state of the task. The possible values include: 'waiting', 'skipped', 'running', 'completed', 'failed', 'canceled' and 'canceling'. */
	readonly state?: string;
	/** The name of task. */
	name: string;
	/** The logging correlation id associated with this task */
	logging_cid: string;
	/**
	 * User who dispatched this task.
	 * @nullable
	 */
	readonly created_by?: string | null;
	/** Timestamp of when this task was identified ready for pickup. */
	readonly unblocked_at?: string;
	/** Timestamp of when this task started execution. */
	readonly started_at?: string;
	/** Timestamp of when this task stopped execution. */
	readonly finished_at?: string;
	/** A JSON Object of a fatal error encountered during the execution of this task. */
	readonly error?: TaskResponseError;
	/**
	 * DEPRECATED - Always null
	 * @nullable
	 */
	readonly worker?: string | null;
	/** The parent task that spawned this task. */
	readonly parent_task?: string;
	/** Any tasks spawned by this task. */
	readonly child_tasks?: readonly string[];
	/** The task group that this task is a member of. */
	readonly task_group?: string;
	readonly progress_reports?: readonly ProgressReportResponse[];
	/** Resources created by this task. */
	readonly created_resources?: readonly string[];
	/** Resources created by this task as PRNs. */
	readonly created_resource_prns?: readonly string[];
	/** A list of resources required by that task. */
	readonly reserved_resources_record?: readonly string[];
	/** The result of this task. */
	readonly result?: unknown;
}
