/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { TasksListOrderingItem } from "./tasksListOrderingItem";
import type { TasksListState } from "./tasksListState";

export type TasksListParams = {
	child_tasks?: string;
	created_resources?: string;
	exclusive_resources?: string;
	/**
	 * Multiple values may be separated by commas.
	 */
	exclusive_resources__in?: string[];
	/**
	 * Filter results where finished_at matches value
	 */
	finished_at?: string;
	/**
	 * Filter results where finished_at is greater than value
	 */
	finished_at__gt?: string;
	/**
	 * Filter results where finished_at is greater than or equal to value
	 */
	finished_at__gte?: string;
	/**
	 * Filter results where finished_at has a null value
	 */
	finished_at__isnull?: boolean;
	/**
	 * Filter results where finished_at is less than value
	 */
	finished_at__lt?: string;
	/**
	 * Filter results where finished_at is less than or equal to value
	 */
	finished_at__lte?: string;
	/**
	 * Filter results where finished_at is between two comma separated values
	 */
	finished_at__range?: string[];
	/**
	 * Number of results to return per page.
	 */
	limit?: number;
	/**
	 * Filter results where logging_cid matches value
	 */
	logging_cid?: string;
	/**
	 * Filter results where logging_cid contains value
	 */
	logging_cid__contains?: string;
	/**
	 * Filter results where name matches value
	 */
	name?: string;
	/**
	 * Filter results where name contains value
	 */
	name__contains?: string;
	/**
	 * Filter results where name is in a comma-separated list of values
	 */
	name__in?: string[];
	/**
	 * Filter results where name not equal to value
	 */
	name__ne?: string;
	/**
	 * The initial index from which to return the results.
	 */
	offset?: number;
	/**
	 * Ordering
	 *
	 * * `pulp_id` - Pulp id
	 * * `-pulp_id` - Pulp id (descending)
	 * * `pulp_created` - Pulp created
	 * * `-pulp_created` - Pulp created (descending)
	 * * `pulp_last_updated` - Pulp last updated
	 * * `-pulp_last_updated` - Pulp last updated (descending)
	 * * `state` - State
	 * * `-state` - State (descending)
	 * * `name` - Name
	 * * `-name` - Name (descending)
	 * * `logging_cid` - Logging cid
	 * * `-logging_cid` - Logging cid (descending)
	 * * `unblocked_at` - Unblocked at
	 * * `-unblocked_at` - Unblocked at (descending)
	 * * `started_at` - Started at
	 * * `-started_at` - Started at (descending)
	 * * `finished_at` - Finished at
	 * * `-finished_at` - Finished at (descending)
	 * * `error` - Error
	 * * `-error` - Error (descending)
	 * * `enc_args` - Enc args
	 * * `-enc_args` - Enc args (descending)
	 * * `enc_kwargs` - Enc kwargs
	 * * `-enc_kwargs` - Enc kwargs (descending)
	 * * `reserved_resources_record` - Reserved resources record
	 * * `-reserved_resources_record` - Reserved resources record (descending)
	 * * `versions` - Versions
	 * * `-versions` - Versions (descending)
	 * * `profile_options` - Profile options
	 * * `-profile_options` - Profile options (descending)
	 * * `immediate` - Immediate
	 * * `-immediate` - Immediate (descending)
	 * * `deferred` - Deferred
	 * * `-deferred` - Deferred (descending)
	 * * `result` - Result
	 * * `-result` - Result (descending)
	 * * `pk` - Pk
	 * * `-pk` - Pk (descending)
	 */
	ordering?: TasksListOrderingItem[];
	parent_task?: string;
	/**
	 * Multiple values may be separated by commas.
	 */
	prn__in?: string[];
	/**
	 * Filter results where pulp_created matches value
	 */
	pulp_created?: string;
	/**
	 * Filter results where pulp_created is greater than value
	 */
	pulp_created__gt?: string;
	/**
	 * Filter results where pulp_created is greater than or equal to value
	 */
	pulp_created__gte?: string;
	/**
	 * Filter results where pulp_created has a null value
	 */
	pulp_created__isnull?: boolean;
	/**
	 * Filter results where pulp_created is less than value
	 */
	pulp_created__lt?: string;
	/**
	 * Filter results where pulp_created is less than or equal to value
	 */
	pulp_created__lte?: string;
	/**
	 * Filter results where pulp_created is between two comma separated values
	 */
	pulp_created__range?: string[];
	/**
	 * Multiple values may be separated by commas.
	 */
	pulp_href__in?: string[];
	/**
	 * Multiple values may be separated by commas.
	 */
	pulp_id__in?: string[];
	/**
	 * Filter results by using NOT, AND and OR operations on other filters
	 */
	q?: string;
	reserved_resources?: string;
	/**
	 * Multiple values may be separated by commas.
	 */
	reserved_resources__in?: string[];
	shared_resources?: string;
	/**
	 * Multiple values may be separated by commas.
	 */
	shared_resources__in?: string[];
	/**
	 * Filter results where started_at matches value
	 */
	started_at?: string;
	/**
	 * Filter results where started_at is greater than value
	 */
	started_at__gt?: string;
	/**
	 * Filter results where started_at is greater than or equal to value
	 */
	started_at__gte?: string;
	/**
	 * Filter results where started_at has a null value
	 */
	started_at__isnull?: boolean;
	/**
	 * Filter results where started_at is less than value
	 */
	started_at__lt?: string;
	/**
	 * Filter results where started_at is less than or equal to value
	 */
	started_at__lte?: string;
	/**
	 * Filter results where started_at is between two comma separated values
	 */
	started_at__range?: string[];
	/**
	 * Filter results where state matches value
	 *
	 * * `waiting` - Waiting
	 * * `skipped` - Skipped
	 * * `running` - Running
	 * * `completed` - Completed
	 * * `failed` - Failed
	 * * `canceled` - Canceled
	 * * `canceling` - Canceling
	 */
	state?: TasksListState;
	/**
	 * Filter results where state is in a comma-separated list of values
	 */
	state__in?: string[];
	/**
	 * Filter results where state not equal to value
	 */
	state__ne?: string;
	task_group?: string;
	/**
	 * Filter results where unblocked_at matches value
	 */
	unblocked_at?: string;
	/**
	 * Filter results where unblocked_at is greater than value
	 */
	unblocked_at__gt?: string;
	/**
	 * Filter results where unblocked_at is greater than or equal to value
	 */
	unblocked_at__gte?: string;
	/**
	 * Filter results where unblocked_at has a null value
	 */
	unblocked_at__isnull?: boolean;
	/**
	 * Filter results where unblocked_at is less than value
	 */
	unblocked_at__lt?: string;
	/**
	 * Filter results where unblocked_at is less than or equal to value
	 */
	unblocked_at__lte?: string;
	/**
	 * Filter results where unblocked_at is between two comma separated values
	 */
	unblocked_at__range?: string[];
	worker?: string;
	/**
	 * A list of fields to include in the response.
	 */
	fields?: string[];
	/**
	 * A list of fields to exclude from the response.
	 */
	exclude_fields?: string[];
};
