/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { RoleResponse } from "./roleResponse";

export interface PaginatedRoleResponseList {
	count: number;
	/** @nullable */
	next?: string | null;
	/** @nullable */
	previous?: string | null;
	results: RoleResponse[];
}
