/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Serializer for Role.
 */
export interface PatchedRole {
	/**
	 * The name of this role.
	 * @minLength 1
	 */
	name?: string;
	/**
	 * An optional description.
	 * @minLength 1
	 * @nullable
	 */
	description?: string | null;
	/** List of permissions defining the role. */
	permissions?: string[];
}
