/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Serializer for Role.
 */
export interface RoleResponse {
	readonly pulp_href?: string;
	/** The Pulp Resource Name (PRN). */
	readonly prn?: string;
	/** Timestamp of creation. */
	readonly pulp_created?: string;
	/** Timestamp of the last time this resource was updated. Note: for immutable resources - like content, repository versions, and publication - pulp_created and pulp_last_updated dates will be the same. */
	readonly pulp_last_updated?: string;
	/** The name of this role. */
	name: string;
	/**
	 * An optional description.
	 * @nullable
	 */
	description?: string | null;
	/** List of permissions defining the role. */
	permissions: string[];
	/** True if the role is system managed. */
	readonly locked?: boolean;
}
