/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { RolesListOrderingItem } from "./rolesListOrderingItem";

export type RolesListParams = {
	/**
	 * Filter roles that have any of the permissions in the list.
	 */
	contains_permission?: string[];
	/**
	 * Filter results where description matches value
	 */
	description?: string;
	/**
	 * Filter results where description contains value
	 */
	description__contains?: string;
	/**
	 * Filter results where description contains value
	 */
	description__icontains?: string;
	/**
	 * Filter results where description matches value
	 */
	description__iexact?: string;
	/**
	 * Filter roles that only have permissions for the specified object HREF.
	 */
	for_object_type?: string;
	/**
	 * Number of results to return per page.
	 */
	limit?: number;
	/**
	 * Filter results where locked matches value
	 */
	locked?: boolean;
	/**
	 * Filter results where name matches value
	 */
	name?: string;
	/**
	 * Filter results where name contains value
	 */
	name__contains?: string;
	/**
	 * Filter results where name contains value
	 */
	name__icontains?: string;
	/**
	 * Filter results where name matches value
	 */
	name__iexact?: string;
	/**
	 * Filter results where name is in a comma-separated list of values
	 */
	name__in?: string[];
	/**
	 * Filter results where name matches regex value
	 */
	name__iregex?: string;
	/**
	 * Filter results where name starts with value
	 */
	name__istartswith?: string;
	/**
	 * Filter results where name matches regex value
	 */
	name__regex?: string;
	/**
	 * Filter results where name starts with value
	 */
	name__startswith?: string;
	/**
	 * The initial index from which to return the results.
	 */
	offset?: number;
	/**
	 * Ordering
	 *
	 * * `pulp_id` - Pulp id
	 * * `-pulp_id` - Pulp id (descending)
	 * * `pulp_created` - Pulp created
	 * * `-pulp_created` - Pulp created (descending)
	 * * `pulp_last_updated` - Pulp last updated
	 * * `-pulp_last_updated` - Pulp last updated (descending)
	 * * `name` - Name
	 * * `-name` - Name (descending)
	 * * `description` - Description
	 * * `-description` - Description (descending)
	 * * `locked` - Locked
	 * * `-locked` - Locked (descending)
	 * * `pk` - Pk
	 * * `-pk` - Pk (descending)
	 */
	ordering?: RolesListOrderingItem[];
	/**
	 * Multiple values may be separated by commas.
	 */
	prn__in?: string[];
	/**
	 * Multiple values may be separated by commas.
	 */
	pulp_href__in?: string[];
	/**
	 * Multiple values may be separated by commas.
	 */
	pulp_id__in?: string[];
	/**
	 * Filter results by using NOT, AND and OR operations on other filters
	 */
	q?: string;
	/**
	 * A list of fields to include in the response.
	 */
	fields?: string[];
	/**
	 * A list of fields to exclude from the response.
	 */
	exclude_fields?: string[];
};
