/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

export type RolesListOrderingItem =
	(typeof RolesListOrderingItem)[keyof typeof RolesListOrderingItem];

export const RolesListOrderingItem = {
	"-description": "-description",
	"-locked": "-locked",
	"-name": "-name",
	"-pk": "-pk",
	"-pulp_created": "-pulp_created",
	"-pulp_id": "-pulp_id",
	"-pulp_last_updated": "-pulp_last_updated",
	description: "description",
	locked: "locked",
	name: "name",
	pk: "pk",
	pulp_created: "pulp_created",
	pulp_id: "pulp_id",
	pulp_last_updated: "pulp_last_updated",
} as const;
