/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

import { pulpFetch } from "../../mutator/pulpFetch";
import type { MyPermissionsResponse } from "../models/myPermissionsResponse";
import type { NestedRole } from "../models/nestedRole";
import type { NestedRoleResponse } from "../models/nestedRoleResponse";
import type { ObjectRolesResponse } from "../models/objectRolesResponse";
import type { AsyncOperationResponse } from "../models/tasks/asyncOperationResponse";
import type { PaginatedTaskResponseList } from "../models/tasks/paginatedTaskResponseList";
import type { PatchedTaskCancel } from "../models/tasks/patchedTaskCancel";
import type { ProfileArtifactResponse } from "../models/tasks/profileArtifactResponse";
import type { Purge } from "../models/tasks/purge";
import type { TaskResponse } from "../models/tasks/taskResponse";
import type { TasksListParams } from "../models/tasks/tasksListParams";
import type { TasksListRolesParams } from "../models/tasks/tasksListRolesParams";
import type { TasksMyPermissionsParams } from "../models/tasks/tasksMyPermissionsParams";
import type { TasksProfileArtifactsParams } from "../models/tasks/tasksProfileArtifactsParams";
import type { TasksReadParams } from "../models/tasks/tasksReadParams";

export const getTasksListUrl = (params?: TasksListParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}

		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/tasks/?${stringifiedParams}`
		: `/pulp/api/v3/tasks/`;
};

/**
 * A customized named ModelViewSet that knows how to register itself with the Pulp API router.
 *
 * This viewset is discoverable by its name.
 * "Normal" Django Models and Master/Detail models are supported by the ``register_with`` method.
 *
 * Attributes:
 *     lookup_field (str): The name of the field by which an object should be looked up, in
 *         addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'
 *     endpoint_name (str): The name of the final path segment that should identify the ViewSet's
 *         collection endpoint.
 *     nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must
 *         correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.
 *         None indicates this ViewSet should not be nested.
 *     parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs
 *         to django model filter expressions that can be used with the corresponding value from
 *         self.kwargs, used only by a nested ViewSet to filter based on the parent object's
 *         identity.
 *     schema (DefaultSchema): The schema class to use by default in a viewset.
 * @summary List tasks
 */
export const tasksList = async (
	params?: TasksListParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<PaginatedTaskResponseList> => {
	return pulpFetch<PaginatedTaskResponseList>(getTasksListUrl(params), {
		...options,
		method: "GET",
	});
};

export const getTasksReadUrl = (pulpId: string, params?: TasksReadParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/tasks/${pulpId}/?${stringifiedParams}`
		: `/pulp/api/v3/tasks/${pulpId}/`;
};

/**
 * A customized named ModelViewSet that knows how to register itself with the Pulp API router.
 *
 * This viewset is discoverable by its name.
 * "Normal" Django Models and Master/Detail models are supported by the ``register_with`` method.
 *
 * Attributes:
 *     lookup_field (str): The name of the field by which an object should be looked up, in
 *         addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'
 *     endpoint_name (str): The name of the final path segment that should identify the ViewSet's
 *         collection endpoint.
 *     nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must
 *         correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.
 *         None indicates this ViewSet should not be nested.
 *     parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs
 *         to django model filter expressions that can be used with the corresponding value from
 *         self.kwargs, used only by a nested ViewSet to filter based on the parent object's
 *         identity.
 *     schema (DefaultSchema): The schema class to use by default in a viewset.
 * @summary Inspect a task
 */
export const tasksRead = async (
	pulpId: string,
	params?: TasksReadParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<TaskResponse> => {
	return pulpFetch<TaskResponse>(getTasksReadUrl(pulpId, params), {
		...options,
		method: "GET",
	});
};

export const getTasksCancelUrl = (pulpId: string) => {
	return `/pulp/api/v3/tasks/${pulpId}/`;
};

/**
 * This operation cancels a task.
 * @summary Cancel a task
 */
export const tasksCancel = async (
	pulpId: string,
	patchedTaskCancel: PatchedTaskCancel,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<TaskResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<TaskResponse>(getTasksCancelUrl(pulpId), {
		...options,
		method: "PATCH",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(patchedTaskCancel),
	});
};

export const getTasksDeleteUrl = (pulpId: string) => {
	return `/pulp/api/v3/tasks/${pulpId}/`;
};

/**
 * A customized named ModelViewSet that knows how to register itself with the Pulp API router.
 *
 * This viewset is discoverable by its name.
 * "Normal" Django Models and Master/Detail models are supported by the ``register_with`` method.
 *
 * Attributes:
 *     lookup_field (str): The name of the field by which an object should be looked up, in
 *         addition to any parent lookups if this ViewSet is nested. Defaults to 'pk'
 *     endpoint_name (str): The name of the final path segment that should identify the ViewSet's
 *         collection endpoint.
 *     nest_prefix (str): Optional prefix under which this ViewSet should be nested. This must
 *         correspond to the "parent_prefix" of a router with rest_framework_nested.NestedMixin.
 *         None indicates this ViewSet should not be nested.
 *     parent_lookup_kwargs (dict): Optional mapping of key names that would appear in self.kwargs
 *         to django model filter expressions that can be used with the corresponding value from
 *         self.kwargs, used only by a nested ViewSet to filter based on the parent object's
 *         identity.
 *     schema (DefaultSchema): The schema class to use by default in a viewset.
 * @summary Delete a task
 */
export const tasksDelete = async (
	pulpId: string,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<void> => {
	return pulpFetch<void>(getTasksDeleteUrl(pulpId), {
		...options,
		method: "DELETE",
	});
};

export const getTasksAddRoleUrl = (pulpId: string) => {
	return `/pulp/api/v3/tasks/${pulpId}/add_role/`;
};

/**
 * Add a role for this object to users/groups.
 * @summary Add a role
 */
export const tasksAddRole = async (
	pulpId: string,
	nestedRole: NestedRole,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<NestedRoleResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<NestedRoleResponse>(getTasksAddRoleUrl(pulpId), {
		...options,
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(nestedRole),
	});
};

export const getTasksListRolesUrl = (
	pulpId: string,
	params?: TasksListRolesParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/tasks/${pulpId}/list_roles/?${stringifiedParams}`
		: `/pulp/api/v3/tasks/${pulpId}/list_roles/`;
};

/**
 * List roles assigned to this object.
 * @summary List roles
 */
export const tasksListRoles = async (
	pulpId: string,
	params?: TasksListRolesParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<ObjectRolesResponse> => {
	return pulpFetch<ObjectRolesResponse>(getTasksListRolesUrl(pulpId, params), {
		...options,
		method: "GET",
	});
};

export const getTasksMyPermissionsUrl = (
	pulpId: string,
	params?: TasksMyPermissionsParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/tasks/${pulpId}/my_permissions/?${stringifiedParams}`
		: `/pulp/api/v3/tasks/${pulpId}/my_permissions/`;
};

/**
 * List permissions available to the current user on this object.
 * @summary List user permissions
 */
export const tasksMyPermissions = async (
	pulpId: string,
	params?: TasksMyPermissionsParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<MyPermissionsResponse> => {
	return pulpFetch<MyPermissionsResponse>(
		getTasksMyPermissionsUrl(pulpId, params),
		{
			...options,
			method: "GET",
		},
	);
};

export const getTasksProfileArtifactsUrl = (
	pulpId: string,
	params?: TasksProfileArtifactsParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/tasks/${pulpId}/profile_artifacts/?${stringifiedParams}`
		: `/pulp/api/v3/tasks/${pulpId}/profile_artifacts/`;
};

/**
 * Return pre-signed URLs used for downloading raw profile artifacts.
 * @summary Fetch downloadable links for profile artifacts
 */
export const tasksProfileArtifacts = async (
	pulpId: string,
	params?: TasksProfileArtifactsParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<ProfileArtifactResponse> => {
	return pulpFetch<ProfileArtifactResponse>(
		getTasksProfileArtifactsUrl(pulpId, params),
		{
			...options,
			method: "GET",
		},
	);
};

export const getTasksRemoveRoleUrl = (pulpId: string) => {
	return `/pulp/api/v3/tasks/${pulpId}/remove_role/`;
};

/**
 * Remove a role for this object from users/groups.
 * @summary Remove a role
 */
export const tasksRemoveRole = async (
	pulpId: string,
	nestedRole: NestedRole,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<NestedRoleResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<NestedRoleResponse>(getTasksRemoveRoleUrl(pulpId), {
		...options,
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(nestedRole),
	});
};

export const getTasksPurgeUrl = () => {
	return `/pulp/api/v3/tasks/purge/`;
};

/**
 * Trigger an asynchronous task that deletes completed tasks that finished prior to a specified timestamp.
 * @summary Purge Completed Tasks
 */
export const tasksPurge = async (
	purge: Purge,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<AsyncOperationResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<AsyncOperationResponse>(getTasksPurgeUrl(), {
		...options,
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(purge),
	});
};
