/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

export interface LoginUpdateResponse {
	/**
	 * 150 characters or fewer. Letters, digits and @/./+/-/_ only.
	 * @maxLength 150
	 */
	username?: string;
	/**
	 * First name
	 * @maxLength 150
	 */
	first_name?: string;
	/**
	 * Last name
	 * @maxLength 150
	 */
	last_name?: string;
	/** Email address */
	email?: string;
}
