/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { GroupsListOrderingItem } from "./groupsListOrderingItem";

export type GroupsListParams = {
	/**
	 * Filter results where id matches value
	 */
	id?: number;
	/**
	 * Filter results where id is in a comma-separated list of values
	 */
	id__in?: number[];
	/**
	 * Number of results to return per page.
	 */
	limit?: number;
	/**
	 * Filter results where name matches value
	 */
	name?: string;
	/**
	 * Filter results where name contains value
	 */
	name__contains?: string;
	/**
	 * Filter results where name contains value
	 */
	name__icontains?: string;
	/**
	 * Filter results where name matches value
	 */
	name__iexact?: string;
	/**
	 * Filter results where name is in a comma-separated list of values
	 */
	name__in?: string[];
	/**
	 * The initial index from which to return the results.
	 */
	offset?: number;
	/**
	 * Ordering
	 *
	 * * `id` - Id
	 * * `-id` - Id (descending)
	 * * `name` - Name
	 * * `-name` - Name (descending)
	 * * `pk` - Pk
	 * * `-pk` - Pk (descending)
	 */
	ordering?: GroupsListOrderingItem[];
	/**
	 * Multiple values may be separated by commas.
	 */
	prn__in?: string[];
	/**
	 * Multiple values may be separated by commas.
	 */
	pulp_href__in?: string[];
	/**
	 * Multiple values may be separated by commas.
	 */
	pulp_id__in?: string[];
	/**
	 * Filter results by using NOT, AND and OR operations on other filters
	 */
	q?: string;
	/**
	 * A list of fields to include in the response.
	 */
	fields?: string[];
	/**
	 * A list of fields to exclude from the response.
	 */
	exclude_fields?: string[];
};
