/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

export type GroupsListOrderingItem =
	(typeof GroupsListOrderingItem)[keyof typeof GroupsListOrderingItem];

export const GroupsListOrderingItem = {
	"-id": "-id",
	"-name": "-name",
	"-pk": "-pk",
	id: "id",
	name: "name",
	pk: "pk",
} as const;
