/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Serializer for User.
 */
export interface PatchedUser {
	/**
	 * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
	 * @minLength 1
	 * @maxLength 150
	 */
	username?: string;
	/**
	 * Users password. Set to ``null`` to disable password authentication.
	 * @minLength 1
	 * @nullable
	 */
	password?: string | null;
	/**
	 * First name
	 * @maxLength 150
	 */
	first_name?: string;
	/**
	 * Last name
	 * @maxLength 150
	 */
	last_name?: string;
	/** Email address */
	email?: string;
	/** Designates whether the user can log into this admin site. */
	is_staff?: boolean;
	/** Designates whether this user should be treated as active. */
	is_active?: boolean;
}
