/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { UsersListOrderingItem } from "./usersListOrderingItem";

export type UsersListParams = {
	/**
	 * Filter results where email matches value
	 */
	email?: string;
	/**
	 * Filter results where email contains value
	 */
	email__contains?: string;
	/**
	 * Filter results where email contains value
	 */
	email__icontains?: string;
	/**
	 * Filter results where email matches value
	 */
	email__iexact?: string;
	/**
	 * Filter results where email is in a comma-separated list of values
	 */
	email__in?: string[];
	/**
	 * Filter results where first_name matches value
	 */
	first_name?: string;
	/**
	 * Filter results where first_name contains value
	 */
	first_name__contains?: string;
	/**
	 * Filter results where first_name contains value
	 */
	first_name__icontains?: string;
	/**
	 * Filter results where first_name matches value
	 */
	first_name__iexact?: string;
	/**
	 * Filter results where first_name is in a comma-separated list of values
	 */
	first_name__in?: string[];
	/**
	 * Filter results where is_active matches value
	 */
	is_active?: boolean;
	/**
	 * Filter results where is_staff matches value
	 */
	is_staff?: boolean;
	/**
	 * Filter results where last_name matches value
	 */
	last_name?: string;
	/**
	 * Filter results where last_name contains value
	 */
	last_name__contains?: string;
	/**
	 * Filter results where last_name contains value
	 */
	last_name__icontains?: string;
	/**
	 * Filter results where last_name matches value
	 */
	last_name__iexact?: string;
	/**
	 * Filter results where last_name is in a comma-separated list of values
	 */
	last_name__in?: string[];
	/**
	 * Number of results to return per page.
	 */
	limit?: number;
	/**
	 * The initial index from which to return the results.
	 */
	offset?: number;
	/**
	 * Ordering
	 *
	 * * `id` - Id
	 * * `-id` - Id (descending)
	 * * `password` - Password
	 * * `-password` - Password (descending)
	 * * `last_login` - Last login
	 * * `-last_login` - Last login (descending)
	 * * `is_superuser` - Is superuser
	 * * `-is_superuser` - Is superuser (descending)
	 * * `username` - Username
	 * * `-username` - Username (descending)
	 * * `first_name` - First name
	 * * `-first_name` - First name (descending)
	 * * `last_name` - Last name
	 * * `-last_name` - Last name (descending)
	 * * `email` - Email
	 * * `-email` - Email (descending)
	 * * `is_staff` - Is staff
	 * * `-is_staff` - Is staff (descending)
	 * * `is_active` - Is active
	 * * `-is_active` - Is active (descending)
	 * * `date_joined` - Date joined
	 * * `-date_joined` - Date joined (descending)
	 * * `pk` - Pk
	 * * `-pk` - Pk (descending)
	 */
	ordering?: UsersListOrderingItem[];
	/**
	 * Multiple values may be separated by commas.
	 */
	prn__in?: string[];
	/**
	 * Multiple values may be separated by commas.
	 */
	pulp_href__in?: string[];
	/**
	 * Multiple values may be separated by commas.
	 */
	pulp_id__in?: string[];
	/**
	 * Filter results by using NOT, AND and OR operations on other filters
	 */
	q?: string;
	/**
	 * Filter results where username matches value
	 */
	username?: string;
	/**
	 * Filter results where username contains value
	 */
	username__contains?: string;
	/**
	 * Filter results where username contains value
	 */
	username__icontains?: string;
	/**
	 * Filter results where username matches value
	 */
	username__iexact?: string;
	/**
	 * Filter results where username is in a comma-separated list of values
	 */
	username__in?: string[];
	/**
	 * A list of fields to include in the response.
	 */
	fields?: string[];
	/**
	 * A list of fields to exclude from the response.
	 */
	exclude_fields?: string[];
};
