/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

/**
 * Serializer for Groups that belong to an User.
 */
export interface UserGroupResponse {
	/**
	 * Name.
	 * @maxLength 150
	 */
	name: string;
	readonly pulp_href?: string;
	readonly prn?: string;
}
