/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

export type UserResponseHiddenFieldsItem = {
	name: string;
	is_set: boolean;
};
