/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */
import type { UserGroupResponse } from "./userGroupResponse";
import type { UserResponseHiddenFieldsItem } from "./userResponseHiddenFieldsItem";

/**
 * Serializer for User.
 */
export interface UserResponse {
	readonly pulp_href?: string;
	readonly prn?: string;
	readonly id?: number;
	/**
	 * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
	 * @maxLength 150
	 */
	username: string;
	/**
	 * First name
	 * @maxLength 150
	 */
	first_name?: string;
	/**
	 * Last name
	 * @maxLength 150
	 */
	last_name?: string;
	/** Email address */
	email?: string;
	/** Designates whether the user can log into this admin site. */
	is_staff?: boolean;
	/** Designates whether this user should be treated as active. */
	is_active?: boolean;
	/** Date joined */
	readonly date_joined?: string;
	readonly groups?: readonly UserGroupResponse[];
	/** List of hidden (write only) fields */
	readonly hidden_fields?: readonly UserResponseHiddenFieldsItem[];
}
