/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

export type UsersListOrderingItem =
	(typeof UsersListOrderingItem)[keyof typeof UsersListOrderingItem];

export const UsersListOrderingItem = {
	"-date_joined": "-date_joined",
	"-email": "-email",
	"-first_name": "-first_name",
	"-id": "-id",
	"-is_active": "-is_active",
	"-is_staff": "-is_staff",
	"-is_superuser": "-is_superuser",
	"-last_login": "-last_login",
	"-last_name": "-last_name",
	"-password": "-password",
	"-pk": "-pk",
	"-username": "-username",
	date_joined: "date_joined",
	email: "email",
	first_name: "first_name",
	id: "id",
	is_active: "is_active",
	is_staff: "is_staff",
	is_superuser: "is_superuser",
	last_login: "last_login",
	last_name: "last_name",
	password: "password",
	pk: "pk",
	username: "username",
} as const;
