/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

import { pulpFetch } from "../../mutator/pulpFetch";
import type { LoginReadParams } from "../models/login/loginReadParams";
import type { LoginResponse } from "../models/login/loginResponse";
import type { LoginUpdateResponse } from "../models/login/loginUpdateResponse";
import type { PatchedLoginUpdate } from "../models/login/patchedLoginUpdate";

export const getLoginReadUrl = (params?: LoginReadParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/login/?${stringifiedParams}`
		: `/pulp/api/v3/login/`;
};

export const loginRead = async (
	params?: LoginReadParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<LoginResponse> => {
	return pulpFetch<LoginResponse>(getLoginReadUrl(params), {
		...options,
		method: "GET",
	});
};

export const getLoginUrl = () => {
	return `/pulp/api/v3/login/`;
};

export const login = async (
	options?: Parameters<typeof pulpFetch>[1],
): Promise<LoginResponse> => {
	return pulpFetch<LoginResponse>(getLoginUrl(), {
		...options,
		method: "POST",
	});
};

export const getLoginUpdateUrl = () => {
	return `/pulp/api/v3/login/`;
};

export const loginUpdate = async (
	patchedLoginUpdate: PatchedLoginUpdate,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<LoginUpdateResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return pulpFetch<LoginUpdateResponse>(getLoginUpdateUrl(), {
		...options,
		method: "PATCH",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(patchedLoginUpdate),
	});
};

export const getLogoutUrl = () => {
	return `/pulp/api/v3/login/`;
};

export const logout = async (
	options?: Parameters<typeof pulpFetch>[1],
): Promise<void> => {
	return pulpFetch<void>(getLogoutUrl(), {
		...options,
		method: "DELETE",
	});
};
