/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

import { pulpFetch } from "../../mutator/pulpFetch";
import type { Group } from "../models/groups/group";
import type { GroupResponse } from "../models/groups/groupResponse";
import type { GroupsListParams } from "../models/groups/groupsListParams";
import type { GroupsListRolesParams } from "../models/groups/groupsListRolesParams";
import type { GroupsMyPermissionsParams } from "../models/groups/groupsMyPermissionsParams";
import type { GroupsReadParams } from "../models/groups/groupsReadParams";
import type { PaginatedGroupResponseList } from "../models/groups/paginatedGroupResponseList";
import type { PatchedGroup } from "../models/groups/patchedGroup";
import type { MyPermissionsResponse } from "../models/myPermissionsResponse";
import type { NestedRole } from "../models/nestedRole";
import type { NestedRoleResponse } from "../models/nestedRoleResponse";
import type { ObjectRolesResponse } from "../models/objectRolesResponse";

export const getGroupsListUrl = (params?: GroupsListParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}

		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/groups/?${stringifiedParams}`
		: `/pulp/api/v3/groups/`;
};

/**
 * ViewSet for Group.
 * @summary List groups
 */
export const groupsList = async (
	params?: GroupsListParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<PaginatedGroupResponseList> => {
	return pulpFetch<PaginatedGroupResponseList>(getGroupsListUrl(params), {
		...options,
		method: "GET",
	});
};

export const getGroupsCreateUrl = () => {
	return `/pulp/api/v3/groups/`;
};

/**
 * ViewSet for Group.
 * @summary Create a group
 */
export const groupsCreate = async (
	group: Group,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<GroupResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<GroupResponse>(getGroupsCreateUrl(), {
		...options,
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(group),
	});
};

export const getGroupsReadUrl = (id: number, params?: GroupsReadParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/groups/${id}/?${stringifiedParams}`
		: `/pulp/api/v3/groups/${id}/`;
};

/**
 * ViewSet for Group.
 * @summary Inspect a group
 */
export const groupsRead = async (
	id: number,
	params?: GroupsReadParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<GroupResponse> => {
	return pulpFetch<GroupResponse>(getGroupsReadUrl(id, params), {
		...options,
		method: "GET",
	});
};

export const getGroupsUpdateUrl = (id: number) => {
	return `/pulp/api/v3/groups/${id}/`;
};

/**
 * ViewSet for Group.
 * @summary Update a group
 */
export const groupsUpdate = async (
	id: number,
	group: Group,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<GroupResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<GroupResponse>(getGroupsUpdateUrl(id), {
		...options,
		method: "PUT",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(group),
	});
};

export const getGroupsPartialUpdateUrl = (id: number) => {
	return `/pulp/api/v3/groups/${id}/`;
};

/**
 * ViewSet for Group.
 * @summary Update a group
 */
export const groupsPartialUpdate = async (
	id: number,
	patchedGroup: PatchedGroup,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<GroupResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<GroupResponse>(getGroupsPartialUpdateUrl(id), {
		...options,
		method: "PATCH",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(patchedGroup),
	});
};

export const getGroupsDeleteUrl = (id: number) => {
	return `/pulp/api/v3/groups/${id}/`;
};

/**
 * ViewSet for Group.
 * @summary Delete a group
 */
export const groupsDelete = async (
	id: number,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<void> => {
	return pulpFetch<void>(getGroupsDeleteUrl(id), {
		...options,
		method: "DELETE",
	});
};

export const getGroupsAddRoleUrl = (id: number) => {
	return `/pulp/api/v3/groups/${id}/add_role/`;
};

/**
 * Add a role for this object to users/groups.
 * @summary Add a role
 */
export const groupsAddRole = async (
	id: number,
	nestedRole: NestedRole,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<NestedRoleResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<NestedRoleResponse>(getGroupsAddRoleUrl(id), {
		...options,
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(nestedRole),
	});
};

export const getGroupsListRolesUrl = (
	id: number,
	params?: GroupsListRolesParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/groups/${id}/list_roles/?${stringifiedParams}`
		: `/pulp/api/v3/groups/${id}/list_roles/`;
};

/**
 * List roles assigned to this object.
 * @summary List roles
 */
export const groupsListRoles = async (
	id: number,
	params?: GroupsListRolesParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<ObjectRolesResponse> => {
	return pulpFetch<ObjectRolesResponse>(getGroupsListRolesUrl(id, params), {
		...options,
		method: "GET",
	});
};

export const getGroupsMyPermissionsUrl = (
	id: number,
	params?: GroupsMyPermissionsParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/groups/${id}/my_permissions/?${stringifiedParams}`
		: `/pulp/api/v3/groups/${id}/my_permissions/`;
};

/**
 * List permissions available to the current user on this object.
 * @summary List user permissions
 */
export const groupsMyPermissions = async (
	id: number,
	params?: GroupsMyPermissionsParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<MyPermissionsResponse> => {
	return pulpFetch<MyPermissionsResponse>(
		getGroupsMyPermissionsUrl(id, params),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGroupsRemoveRoleUrl = (id: number) => {
	return `/pulp/api/v3/groups/${id}/remove_role/`;
};

/**
 * Remove a role for this object from users/groups.
 * @summary Remove a role
 */
export const groupsRemoveRole = async (
	id: number,
	nestedRole: NestedRole,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<NestedRoleResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<NestedRoleResponse>(getGroupsRemoveRoleUrl(id), {
		...options,
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(nestedRole),
	});
};
