/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

import { pulpFetch } from "../../mutator/pulpFetch";
import type { PaginatedUserResponseList } from "../models/users/paginatedUserResponseList";
import type { PatchedUser } from "../models/users/patchedUser";
import type { User } from "../models/users/user";
import type { UserResponse } from "../models/users/userResponse";
import type { UsersListParams } from "../models/users/usersListParams";
import type { UsersReadParams } from "../models/users/usersReadParams";

export const getUsersListUrl = (params?: UsersListParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}

		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/users/?${stringifiedParams}`
		: `/pulp/api/v3/users/`;
};

/**
 * ViewSet for User.
 * @summary List users
 */
export const usersList = async (
	params?: UsersListParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<PaginatedUserResponseList> => {
	return pulpFetch<PaginatedUserResponseList>(getUsersListUrl(params), {
		...options,
		method: "GET",
	});
};

export const getUsersCreateUrl = () => {
	return `/pulp/api/v3/users/`;
};

/**
 * ViewSet for User.
 * @summary Create an user
 */
export const usersCreate = async (
	user: User,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<UserResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return pulpFetch<UserResponse>(getUsersCreateUrl(), {
		...options,
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(user),
	});
};

export const getUsersReadUrl = (id: number, params?: UsersReadParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/users/${id}/?${stringifiedParams}`
		: `/pulp/api/v3/users/${id}/`;
};

/**
 * ViewSet for User.
 * @summary Inspect an user
 */
export const usersRead = async (
	id: number,
	params?: UsersReadParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<UserResponse> => {
	return pulpFetch<UserResponse>(getUsersReadUrl(id, params), {
		...options,
		method: "GET",
	});
};

export const getUsersUpdateUrl = (id: number) => {
	return `/pulp/api/v3/users/${id}/`;
};

/**
 * ViewSet for User.
 * @summary Update an user
 */
export const usersUpdate = async (
	id: number,
	user: User,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<UserResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return pulpFetch<UserResponse>(getUsersUpdateUrl(id), {
		...options,
		method: "PUT",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(user),
	});
};

export const getUsersPartialUpdateUrl = (id: number) => {
	return `/pulp/api/v3/users/${id}/`;
};

/**
 * ViewSet for User.
 * @summary Update an user
 */
export const usersPartialUpdate = async (
	id: number,
	patchedUser: PatchedUser,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<UserResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Array.isArray(h)) return Object.fromEntries(h);
		return h;
	};
	return pulpFetch<UserResponse>(getUsersPartialUpdateUrl(id), {
		...options,
		method: "PATCH",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(patchedUser),
	});
};

export const getUsersDeleteUrl = (id: number) => {
	return `/pulp/api/v3/users/${id}/`;
};

/**
 * ViewSet for User.
 * @summary Delete an user
 */
export const usersDelete = async (
	id: number,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<void> => {
	return pulpFetch<void>(getUsersDeleteUrl(id), {
		...options,
		method: "DELETE",
	});
};
