/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pulp 3 API
 * Fetch, Upload, Organize, and Distribute Software Packages
 * OpenAPI spec version: v3
 */

import { pulpFetch } from "../../mutator/pulpFetch";
import type { PaginatedRoleResponseList } from "../models/roles/paginatedRoleResponseList";
import type { PatchedRole } from "../models/roles/patchedRole";
import type { Role } from "../models/roles/role";
import type { RoleResponse } from "../models/roles/roleResponse";
import type { RolesListParams } from "../models/roles/rolesListParams";
import type { RolesReadParams } from "../models/roles/rolesReadParams";

export const getRolesListUrl = (params?: RolesListParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = [
			"contains_permission",
			"fields",
			"exclude_fields",
		];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}

		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/roles/?${stringifiedParams}`
		: `/pulp/api/v3/roles/`;
};

/**
 * ViewSet for Role.
 * @summary List roles
 */
export const rolesList = async (
	params?: RolesListParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<PaginatedRoleResponseList> => {
	return pulpFetch<PaginatedRoleResponseList>(getRolesListUrl(params), {
		...options,
		method: "GET",
	});
};

export const getRolesCreateUrl = () => {
	return `/pulp/api/v3/roles/`;
};

/**
 * ViewSet for Role.
 * @summary Create a role
 */
export const rolesCreate = async (
	role: Role,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<RoleResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<RoleResponse>(getRolesCreateUrl(), {
		...options,
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(role),
	});
};

export const getRolesReadUrl = (pulpId: string, params?: RolesReadParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		const explodeParameters = ["fields", "exclude_fields"];

		if (Array.isArray(value) && explodeParameters.includes(key)) {
			value.forEach((v) => {
				normalizedParams.append(key, v === null ? "null" : String(v));
			});
			return;
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/pulp/api/v3/roles/${pulpId}/?${stringifiedParams}`
		: `/pulp/api/v3/roles/${pulpId}/`;
};

/**
 * ViewSet for Role.
 * @summary Inspect a role
 */
export const rolesRead = async (
	pulpId: string,
	params?: RolesReadParams,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<RoleResponse> => {
	return pulpFetch<RoleResponse>(getRolesReadUrl(pulpId, params), {
		...options,
		method: "GET",
	});
};

export const getRolesUpdateUrl = (pulpId: string) => {
	return `/pulp/api/v3/roles/${pulpId}/`;
};

/**
 * ViewSet for Role.
 * @summary Update a role
 */
export const rolesUpdate = async (
	pulpId: string,
	role: Role,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<RoleResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<RoleResponse>(getRolesUpdateUrl(pulpId), {
		...options,
		method: "PUT",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(role),
	});
};

export const getRolesPartialUpdateUrl = (pulpId: string) => {
	return `/pulp/api/v3/roles/${pulpId}/`;
};

/**
 * ViewSet for Role.
 * @summary Update a role
 */
export const rolesPartialUpdate = async (
	pulpId: string,
	patchedRole: PatchedRole,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<RoleResponse> => {
	const getHeaders = (
		h?: NonNullable<RequestInit["headers"]>,
	): Record<string, string | readonly string[]> => {
		if (!h) return {};
		if (h instanceof Headers) return Object.fromEntries(h.entries());
		if (Symbol.iterator in h) {
			return Object.fromEntries(
				Array.from(
					h as Iterable<Iterable<string>>,
					(entry) => Array.from(entry) as [string, string],
				),
			);
		}
		const headers: Record<string, string | readonly string[]> = {};
		for (const [name, value] of Object.entries<
			string | readonly string[] | undefined
		>(h)) {
			if (value !== undefined) headers[name] = value;
		}
		return headers;
	};
	return pulpFetch<RoleResponse>(getRolesPartialUpdateUrl(pulpId), {
		...options,
		method: "PATCH",
		headers: {
			"Content-Type": "application/json",
			...getHeaders(options?.headers),
		},
		body: JSON.stringify(patchedRole),
	});
};

export const getRolesDeleteUrl = (pulpId: string) => {
	return `/pulp/api/v3/roles/${pulpId}/`;
};

/**
 * ViewSet for Role.
 * @summary Delete a role
 */
export const rolesDelete = async (
	pulpId: string,
	options?: Parameters<typeof pulpFetch>[1],
): Promise<void> => {
	return pulpFetch<void>(getRolesDeleteUrl(pulpId), {
		...options,
		method: "DELETE",
	});
};
